// src/constants/teams.js
// Local team data used as authoritative profile fields (contact, expertise, contributions).
// The Team.jsx component will still attempt to fetch GitHub public data for live stats.

export const teamMembers = [
  {
    username: "peter-mwau",
    name: "Peter Mwau",
    position: "Full Stack Developer",
    email: "pierremwau4050@gmail.com",
    linkedin: "https://www.linkedin.com/in/peter-kyale-6b11a4233/",
    website: "https://petermwauportfolio.netlify.app/",
    expertise: ["Solidity", "React", "Node.js", "MongoDB", "TypeScript", "Web3", "DApp"],
    yearsAtCompany: 1,
    skills: [
      { name: "Solidity", level: 85 },
      { name: "React", level: 95 },
      { name: "MongoDB", level: 90 },
      { name: "Web3", level: 80 },
      { name: "JavaScript", level: 92 },
      { name: "Node.js", level: 90 },
      { name: "TypeScript", level: 88 },
    ],
    contributions: [
      "Led the development of Nyota's core platform",
      "Optimized smart contract performance, reducing gas costs by 30%",
      "Integrated third-party APIs for enhanced functionality",
      "Collaborated with cross-functional teams to deliver projects on time",
      "Developed and maintained comprehensive documentation for internal use",
      "Conducted code reviews to ensure adherence to best practices",
      "Implemented CI/CD pipeline for faster deployments",
      "Mentored junior developers in modern web practices",
    ],
    // fallback avatar if GitHub fetch fails
    avatarFallback: "/avatars/peter.png",
    location: "Nairobi, Kenya",
    bio: "Full-stack & blockchain engineer focused on secure smart contracts and scalable dapps."
  },
  {
    username: "NORMTOSH",
    name: "Norman Gitonga",
    position: "Frontend Developer",
    email: "normangitonga388@gmail.com",
    linkedin: "https://www.linkedin.com/in/normangitonga",
    website: "",
    expertise: ["React", "UI/UX", "Tailwind"],
    yearsAtCompany: 2,
    skills: [
      { name: "React", level: 92 },
      { name: "CSS/Tailwind", level: 95 },
      { name: "JavaScript", level: 90 },
      { name: "HTML5", level: 88 },
      { name: "TypeScript", level: 80 },
      { name: "UI/UX Design", level: 85 },
    ],
    contributions: [
      "Designed and implemented responsive UI components",
      "Collaborated with designers to enhance user experience",
      "Spearheaded the adoption of Tailwind CSS across projects",
      "Organized frontend knowledge-sharing sessions for the team",
      "Developed a design system to ensure UI consistency across applications",
      "Integrated third-party APIs to enhance application functionality",
      "Conducted user testing sessions to gather feedback for UI improvements",
      "Created interactive prototypes to streamline the design process",
    ],
    avatarFallback: "/avatars/norman.png",
    location: "Nairobi, Kenya",
    bio: "Frontend engineer passionate about beautiful, accessible interfaces."
  },
  {
    username: "Mickmacha",
    name: "Mike Macha",
    position: "Backend Developer",
    email: "mickmacha@example.com",
    linkedin: "https://linkedin.com/in/mickmacha",
    website: "",
    expertise: ["Python", "Django", "PostgreSQL"],
    yearsAtCompany: 2,
    skills: [
      { name: "Python", level: 93 },
      { name: "Django", level: 90 },
      { name: "PostgreSQL", level: 87 },
      { name: "API Design", level: 89 },
    ],
    contributions: [
      "Architected scalable backend infrastructure",
      "Developed RESTful APIs consumed by frontend applications",
      "Implemented database optimizations improving query performance",
      "Collaborated with frontend developers to define API contracts",
      "Integrated caching mechanisms to enhance application speed",
      "Ensured security best practices in all backend services",
      "Wrote unit and integration tests to maintain code quality",
      "Implemented secure authentication system",
      "Reduced API response time by 50%",
    ],
    avatarFallback: "/avatars/mike.png",
    location: "Nairobi, Kenya",
    bio: "Backend engineer building reliable APIs and data systems."
  },
  {
    username: "AdoyoClifford",
    name: "Aduyo Clifford",
    position: "DevOps Engineer",
    email: "adoyoclifford@example.com",
    linkedin: "https://linkedin.com/in/adoyo-clifford",
    website: "",
    expertise: ["Docker", "Kubernetes", "AWS"],
    yearsAtCompany: 1,
    skills: [
      { name: "Docker", level: 91 },
      { name: "Kubernetes", level: 88 },
      { name: "AWS", level: 86 },
      { name: "CI/CD", level: 90 },
    ],
    contributions: [
      "Set up automated deployment pipelines",
      "Managed cloud infrastructure on AWS",
      "Implemented containerization using Docker and Kubernetes",
      "Monitored system performance and optimized resource usage",
      "Established infrastructure as code practices using Terraform",
      "Improved deployment frequency and reduced lead time for changes",
      "Enhanced system reliability with automated scaling solutions",
      "Reduced infrastructure costs by 30%",
      "Implemented monitoring and alerting systems",
    ],
    avatarFallback: "/avatars/adoyo.png",
    location: "Nairobi, Kenya",
    bio: "DevOps engineer focused on resilience, automation and scale."
  },
];
